name: Holiday Extras - Hungry Geek
description: Holiday Extras Geek Blog
markdown: kramdown
kramdown:
  input: GFM
highlighter: true
permalink: pretty
baseurl: /
prose:
  rooturl: '_posts'
  siteurl: 'http://holidayextras.github.io/'
