name: Holiday Extras - Hungry Geek
description: Holiday Extras Geek Blog
markdown: kramdown
kramdown:
  input: GFM
highlighter: true
permalink: pretty
baseurl: /blog/
paginate: 5
prose:
  rooturl: '_posts'
  siteurl: 'http://holidayextras.github.io/'
  ignore:
    - index.html
    - feed.xml
    - holidayextras.sublime-project
    - .gitignore
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - /projects
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"  
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Your full name"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Blog title"
      - name: "date"
        field:
          element: "hidden"
          type: "text"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "text"
          type: "text"
          placeholder: "NodeJS"
          label: "Categories"
      - name: "tags"
        field:
          element: "text"
          type: "text"
          label: "Searchable tags"
      - name: "comments"
        field:
          element: "select"
          options:
            - name: 'Yes'
              value: 'true'
            - name: 'No'
              value: 'false'
          label: "Allow people to comment on your post?"
      - name: "time"
        field:
          element: "text"
          type: "text"
          label: "Time it takes to read your post"
          placeholder: "5 mins"